version: '3.6'
services:
  web:
    image: nginx
    labels:
      traefik.enable: true
      traefik.http.port: 80
      traefik.http.frontend.rule: "Host: demo.localhost.tv"
    ports:
      - 80
      - 443
    volumes:
      - ./project:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/demo.conf:/etc/nginx/sites-enabled/demo.conf
    restart: always
    depends_on:
      - php
    user: "${VOLUME_USER_ID:-www-data}:www-data"
    networks:
      sfdemo:
        aliases:
          - demo.localhost.tv

  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE:-Europe/Paris}
    ports:
      - 3306
    networks:
      - sfdemo

  php:
    build: .docker/php
    restart: always
    volumes:
      - ./project:/var/www
      - ${COMPOSER_HOME:-/tmp/composer}:/home/www-data/.composer # Share composer cache
    depends_on:
      - db
    user: "${VOLUME_USER_ID:-www-data}:www-data"
    networks:
      - sfdemo

networks:
  sfdemo:
    driver: bridge
