version: '3.6'
services:
  web:
    image: nginx
    labels:
      traefik.enable: true
      traefik.docker.network: sfdemo
      traefik.http.services.www.loadbalancer.server.port: 80
      traefik.http.routers.www.rule: "Host(`demo.localhost.tv`)"
      traefik.http.routers.www.entrypoints: web
    ports:
      - 80
      - 443
    volumes:
      - ../../project:/var/www/project/demo
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/sites:/etc/nginx/sites-enabled
    restart: unless-stopped
    depends_on:
      - php
    networks:
      sfdemo:
        aliases:
          - demo.localhost.tv

  db:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TIMEZONE:-Europe/Paris}
    ports:
      - 3306
    networks:
      - sfdemo

  php:
    build: ../php
    restart: unless-stopped
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ../../project:/var/www/project/demo
      - ~/.cache/composer:/.composer # Share composer cache
    depends_on:
      - db
    user: "${VOLUME_USER_ID:-www-data}:www-data"
    networks:
      - sfdemo

networks:
  sfdemo:
    driver: bridge
