version: '3.6'
services:
  db:
    build:
      context: ../mysql
      args:
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        MYSQL_PORT: ${DB_PORT}
    ports:
      - 33060:3306 # Reserve port to localhost for database connexion on phpstorm
    volumes:
      - mysql-db:/var/lib/mysql

  traefik:
    image: traefik:v2.3
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - sfdemo

volumes:
  mysql-db: #Keep database on local docker storage
